/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.dimas.bridging.app.view;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author yhawin
 */
public class JPanelGenerateExtractPokari extends javax.swing.JPanel {

    /**
     * Creates new form JPanelGenerateExtractPokari
     */
    public JPanelGenerateExtractPokari() {
        initComponents();
    }
    public void resetTeks(){
        getTextPathOutput().setText("");
        getjDateChooserExtract().setDate(new java.util.Date());
    }

    public JButton getBtnExtractAll() {
        return btnExtractAll;
    }

    public JButton getBtnExtractArCustomer() {
        return btnExtractArCustomer;
    }

    public JButton getBtnExtractCanDDeliveryOrder() {
        return btnExtractCanDDeliveryOrder;
    }

    public JButton getBtnExtractCanDDeliveryOrderItemDetail() {
        return btnExtractCanDDeliveryOrderItemDetail;
    }

    public JButton getBtnExtractCanDDeliveryOrderItemDisc() {
        return btnExtractCanDDeliveryOrderItemDisc;
    }

    public JButton getBtnExtractSpEmployee() {
        return btnExtractSpEmployee;
    }

    public JButton getBtnExtractSpEmployeeTargetItemDetail() {
        return btnExtractSpEmployeeTargetItemDetail;
    }

  
    public JButton getBtnExtractSpEmployeeTarget() {
        return btnExtractSpEmployeeTarget;
    }

    public JButton getBtnKirimByEmail() {
        return btnKirimByEmail;
    }

    public JButton getBtnPathOutput() {
        return btnPathOutput;
    }

    public JDateChooser getjDateChooserExtract() {
        return jDateChooserExtract;
    }

    public JTextField getTextPathOutput() {
        return textPathOutput;
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSubGenerateExtractPokari = new javax.swing.JPanel();
        textPathOutput = new javax.swing.JTextField();
        btnPathOutput = new javax.swing.JButton();
        btnExtractCanDDeliveryOrder = new javax.swing.JButton();
        btnExtractCanDDeliveryOrderItemDetail = new javax.swing.JButton();
        btnExtractCanDDeliveryOrderItemDisc = new javax.swing.JButton();
        jLabel88 = new javax.swing.JLabel();
        btnExtractAll = new javax.swing.JButton();
        jDateChooserExtract = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/####",'_');
        btnKirimByEmail = new javax.swing.JButton();
        btnExtractSpEmployee = new javax.swing.JButton();
        btnExtractSpEmployeeTarget = new javax.swing.JButton();
        btnExtractSpEmployeeTargetItemDetail = new javax.swing.JButton();
        btnExtractArCustomer = new javax.swing.JButton();

        jPanelSubGenerateExtractPokari.setBorder(null);

        textPathOutput.setText("jTextField10");

        btnPathOutput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/folder_download_16x16.png"))); // NOI18N

        btnExtractCanDDeliveryOrder.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnExtractCanDDeliveryOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/folder_download2_16x16.png"))); // NOI18N
        btnExtractCanDDeliveryOrder.setText("DDeliveryOrder");

        btnExtractCanDDeliveryOrderItemDetail.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnExtractCanDDeliveryOrderItemDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/folder_download2_16x16.png"))); // NOI18N
        btnExtractCanDDeliveryOrderItemDetail.setText("DDeliveryOrderItemDetail");

        btnExtractCanDDeliveryOrderItemDisc.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnExtractCanDDeliveryOrderItemDisc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/folder_download2_16x16.png"))); // NOI18N
        btnExtractCanDDeliveryOrderItemDisc.setText("DDeliveryOrderItemDisc");

        jLabel88.setText("Path");

        btnExtractAll.setText("Extract All");

        jDateChooserExtract.setDateFormatString("dd/MM/yyyy");

        btnKirimByEmail.setText("Kirim By Email");
        btnKirimByEmail.setEnabled(false);

        btnExtractSpEmployee.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnExtractSpEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/folder_download2_16x16.png"))); // NOI18N
        btnExtractSpEmployee.setText("SpEmployee");

        btnExtractSpEmployeeTarget.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnExtractSpEmployeeTarget.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/folder_download2_16x16.png"))); // NOI18N
        btnExtractSpEmployeeTarget.setText("SpEmployeeTarget");

        btnExtractSpEmployeeTargetItemDetail.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnExtractSpEmployeeTargetItemDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/folder_download2_16x16.png"))); // NOI18N
        btnExtractSpEmployeeTargetItemDetail.setText("SpEmployeeTargetDetail");

        btnExtractArCustomer.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnExtractArCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/folder_download2_16x16.png"))); // NOI18N
        btnExtractArCustomer.setText("ArCustomer");

        javax.swing.GroupLayout jPanelSubGenerateExtractPokariLayout = new javax.swing.GroupLayout(jPanelSubGenerateExtractPokari);
        jPanelSubGenerateExtractPokari.setLayout(jPanelSubGenerateExtractPokariLayout);
        jPanelSubGenerateExtractPokariLayout.setHorizontalGroup(
            jPanelSubGenerateExtractPokariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubGenerateExtractPokariLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSubGenerateExtractPokariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSubGenerateExtractPokariLayout.createSequentialGroup()
                        .addComponent(jLabel88)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPathOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPathOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserExtract, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnExtractAll, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSubGenerateExtractPokariLayout.createSequentialGroup()
                        .addComponent(btnExtractArCustomer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExtractCanDDeliveryOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExtractCanDDeliveryOrderItemDetail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExtractCanDDeliveryOrderItemDisc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExtractSpEmployee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExtractSpEmployeeTarget)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSubGenerateExtractPokariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKirimByEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExtractSpEmployeeTargetItemDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanelSubGenerateExtractPokariLayout.setVerticalGroup(
            jPanelSubGenerateExtractPokariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubGenerateExtractPokariLayout.createSequentialGroup()
                .addGroup(jPanelSubGenerateExtractPokariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPathOutput)
                    .addGroup(jPanelSubGenerateExtractPokariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelSubGenerateExtractPokariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExtractAll)
                            .addComponent(btnKirimByEmail))
                        .addComponent(jDateChooserExtract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSubGenerateExtractPokariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textPathOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel88)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSubGenerateExtractPokariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSubGenerateExtractPokariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExtractSpEmployeeTarget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExtractSpEmployeeTargetItemDetail))
                    .addGroup(jPanelSubGenerateExtractPokariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExtractArCustomer)
                        .addComponent(btnExtractCanDDeliveryOrder)
                        .addComponent(btnExtractCanDDeliveryOrderItemDetail)
                        .addComponent(btnExtractCanDDeliveryOrderItemDisc)
                        .addComponent(btnExtractSpEmployee)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSubGenerateExtractPokari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelSubGenerateExtractPokari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExtractAll;
    private javax.swing.JButton btnExtractArCustomer;
    private javax.swing.JButton btnExtractCanDDeliveryOrder;
    private javax.swing.JButton btnExtractCanDDeliveryOrderItemDetail;
    private javax.swing.JButton btnExtractCanDDeliveryOrderItemDisc;
    private javax.swing.JButton btnExtractSpEmployee;
    private javax.swing.JButton btnExtractSpEmployeeTarget;
    private javax.swing.JButton btnExtractSpEmployeeTargetItemDetail;
    private javax.swing.JButton btnKirimByEmail;
    private javax.swing.JButton btnPathOutput;
    private com.toedter.calendar.JDateChooser jDateChooserExtract;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JPanel jPanelSubGenerateExtractPokari;
    private javax.swing.JTextField textPathOutput;
    // End of variables declaration//GEN-END:variables
}
