/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.dimas.bridging.app.view;

import com.toedter.calendar.JDateChooser;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author yhawin
 */
public class JPanelGenerateExtractBaygon extends javax.swing.JPanel {

    /**
     * Creates new form JPanelGenerateExtractPokari
     */
    public JPanelGenerateExtractBaygon() {
        initComponents();
    }
    
    public void resetTeks(){
        getTextPathOutput().setText("");
        getjDateChooserExtract().setDate(new java.util.Date());
    }
    
    public JButton getBtnExtractAll() {
        return btnExtractAll;
    }

    public JButton getBtnExtractClient() {
        return btnExtractClient;
    }

    public JButton getBtnExtractSales() {
        return btnExtractSales;
    }

    public JButton getBtnExtractSo() {
        return btnExtractSo;
    }

    public JButton getBtnExtractStock() {
        return btnExtractStock;
    }

    public JButton getBtnKirimByEmail() {
        return btnKirimByEmail;
    }

    public JButton getBtnPathOutput() {
        return btnPathOutput;
    }

    public JDateChooser getjDateChooserExtract() {
        return jDateChooserExtract;
    }

    public JTextField getTextPathOutput() {
        return textPathOutput;
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel20 = new javax.swing.JPanel();
        textPathOutput = new javax.swing.JTextField();
        btnPathOutput = new javax.swing.JButton();
        btnExtractSales = new javax.swing.JButton();
        btnExtractStock = new javax.swing.JButton();
        btnExtractClient = new javax.swing.JButton();
        btnExtractSo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnExtractAll = new javax.swing.JButton();
        jDateChooserExtract = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/####",'_');
        btnKirimByEmail = new javax.swing.JButton();

        setBorder(null);

        jPanel20.setBorder(null);

        textPathOutput.setText("jTextField10");

        btnPathOutput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/folder_download_16x16.png"))); // NOI18N

        btnExtractSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/folder_download2_16x16.png"))); // NOI18N
        btnExtractSales.setText("Sales");

        btnExtractStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/folder_download2_16x16.png"))); // NOI18N
        btnExtractStock.setText("Stock");

        btnExtractClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/folder_download2_16x16.png"))); // NOI18N
        btnExtractClient.setText("Client");

        btnExtractSo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/folder_download2_16x16.png"))); // NOI18N
        btnExtractSo.setText("SO");

        jLabel10.setText("Path");

        btnExtractAll.setText("Extract All");

        jDateChooserExtract.setDateFormatString("dd/MM/yyyy");

        btnKirimByEmail.setText("Kirim By Email");
        btnKirimByEmail.setEnabled(false);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(6, 6, 6)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserExtract, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(textPathOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPathOutput)))
                .addGap(49, 49, 49)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(btnExtractSales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExtractStock))
                    .addComponent(btnExtractAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(btnKirimByEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                        .addGap(178, 178, 178))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(btnExtractClient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExtractSo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDateChooserExtract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textPathOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPathOutput)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnExtractStock)
                                .addComponent(btnExtractClient)
                                .addComponent(btnExtractSo))
                            .addComponent(btnExtractSales))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKirimByEmail)
                            .addComponent(btnExtractAll))))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExtractAll;
    private javax.swing.JButton btnExtractClient;
    private javax.swing.JButton btnExtractSales;
    private javax.swing.JButton btnExtractSo;
    private javax.swing.JButton btnExtractStock;
    private javax.swing.JButton btnKirimByEmail;
    private javax.swing.JButton btnPathOutput;
    private com.toedter.calendar.JDateChooser jDateChooserExtract;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JTextField textPathOutput;
    // End of variables declaration//GEN-END:variables
}
