/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.dimas.bridging.app.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTable;

/**
 *
 * @author yhawin
 */
public class JPanelSubOutputKek extends javax.swing.JPanel {

    /**
     * Creates new form JPanelSubOutputKek
     */
    public JPanelSubOutputKek() {
        initComponents();
    }

    public JButton getBtnOutputTAdjstkReload() {
        return btnOutputTAdjstkReload;
    }

    public JButton getBtnOutputTDatdprReload() {
        return btnOutputTDatdprReload;
    }

    public JButton getBtnOutputTDatdslReload() {
        return btnOutputTDatdslReload;
    }

    public JButton getBtnOutputTDatdsrReload() {
        return btnOutputTDatdsrReload;
    }

    public JButton getBtnOutputTDatsriReload() {
        return btnOutputTDatsriReload;
    }

    public JButton getBtnOutputTOutletReload() {
        return btnOutputTOutletReload;
    }

    public JButton getBtnOutputTSalesmanReload() {
        return btnOutputTSalesmanReload;
    }

    public JButton getBtnOutputTStokReload() {
        return btnOutputTStokReload;
    }

    public JPanel getjPanelSubOutputKekMSalesman() {
        return jPanelSubOutputKekMSalesman;
    }

    public JPanel getjPanelSubOutputKekMslout() {
        return jPanelSubOutputKekMslout;
    }

    public JPanel getjPanelSubOutputKekTStok() {
        return jPanelSubOutputKekTStok;
    }

    public JPanel getjPanelSubOutputKekTadjstk() {
        return jPanelSubOutputKekTadjstk;
    }

    public JPanel getjPanelSubOutputKekTdatdpr() {
        return jPanelSubOutputKekTdatdpr;
    }

    public JPanel getjPanelSubOutputKekTdatdsl() {
        return jPanelSubOutputKekTdatdsl;
    }

    public JPanel getjPanelSubOutputKekTdatdsr() {
        return jPanelSubOutputKekTdatdsr;
    }

    public JPanel getjPanelSubOutputKekTdatsri() {
        return jPanelSubOutputKekTdatsri;
    }

    public JTabbedPane getjTabbedPaneUtamaOutputKEK() {
        return jTabbedPaneUtamaOutputKEK;
    }

    public JLabel getLblOutputTAdjstkFooterInfo() {
        return lblOutputTAdjstkFooterInfo;
    }

    public JLabel getLblOutputTDatdprFooterInfo() {
        return lblOutputTDatdprFooterInfo;
    }

    public JLabel getLblOutputTDatdslFooterInfo() {
        return lblOutputTDatdslFooterInfo;
    }

    public JLabel getLblOutputTDatdsrFooterInfo() {
        return lblOutputTDatdsrFooterInfo;
    }

    public JLabel getLblOutputTDatsriFooterInfo() {
        return lblOutputTDatsriFooterInfo;
    }

    public JTable getTableOutputTAdjstk() {
        return tableOutputTAdjstk;
    }

    public JTable getTableOutputTDatdpr() {
        return tableOutputTDatdpr;
    }

    public JTable getTableOutputTDatdsl() {
        return tableOutputTDatdsl;
    }

    public JTable getTableOutputTDatdsr() {
        return tableOutputTDatdsr;
    }

    public JTable getTableOutputTDatsri() {
        return tableOutputTDatsri;
    }

    public JTable getTableOutputTOutlet() {
        return tableOutputTOutlet;
    }

    public JTable getTableOutputTSalesman() {
        return tableOutputTSalesman;
    }

    public JTable getTableOutputTStok() {
        return tableOutputTStok;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneUtamaOutputKEK = new javax.swing.JTabbedPane();
        jPanelSubOutputKekMSalesman = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        btnOutputTSalesmanReload = new javax.swing.JButton();
        jPanel45 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tableOutputTSalesman = new javax.swing.JTable();
        jPanelSubOutputKekTStok = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        btnOutputTStokReload = new javax.swing.JButton();
        jPanel47 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        tableOutputTStok = new javax.swing.JTable();
        jPanelSubOutputKekMslout = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        btnOutputTOutletReload = new javax.swing.JButton();
        jPanel49 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        tableOutputTOutlet = new javax.swing.JTable();
        jPanelSubOutputKekTdatdsl = new javax.swing.JPanel();
        jPanel50 = new javax.swing.JPanel();
        btnOutputTDatdslReload = new javax.swing.JButton();
        lblOutputTDatdslFooterInfo = new javax.swing.JLabel();
        jPanel51 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        tableOutputTDatdsl = new javax.swing.JTable();
        jPanelSubOutputKekTdatdsr = new javax.swing.JPanel();
        jPanel83 = new javax.swing.JPanel();
        btnOutputTDatdsrReload = new javax.swing.JButton();
        lblOutputTDatdsrFooterInfo = new javax.swing.JLabel();
        jScrollPane33 = new javax.swing.JScrollPane();
        tableOutputTDatdsr = new javax.swing.JTable();
        jPanelSubOutputKekTdatdpr = new javax.swing.JPanel();
        jPanel84 = new javax.swing.JPanel();
        btnOutputTDatdprReload = new javax.swing.JButton();
        lblOutputTDatdprFooterInfo = new javax.swing.JLabel();
        jScrollPane34 = new javax.swing.JScrollPane();
        tableOutputTDatdpr = new javax.swing.JTable();
        jPanelSubOutputKekTdatsri = new javax.swing.JPanel();
        jPanel85 = new javax.swing.JPanel();
        btnOutputTDatsriReload = new javax.swing.JButton();
        lblOutputTDatsriFooterInfo = new javax.swing.JLabel();
        jScrollPane35 = new javax.swing.JScrollPane();
        tableOutputTDatsri = new javax.swing.JTable();
        jPanelSubOutputKekTadjstk = new javax.swing.JPanel();
        jPanel86 = new javax.swing.JPanel();
        btnOutputTAdjstkReload = new javax.swing.JButton();
        lblOutputTAdjstkFooterInfo = new javax.swing.JLabel();
        jScrollPane36 = new javax.swing.JScrollPane();
        tableOutputTAdjstk = new javax.swing.JTable();

        jPanel44.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnOutputTSalesmanReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/sync_16x16.png"))); // NOI18N
        btnOutputTSalesmanReload.setText("Reload");

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOutputTSalesmanReload, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(845, Short.MAX_VALUE))
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOutputTSalesmanReload)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel45.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tableOutputTSalesman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane11.setViewportView(tableOutputTSalesman);

        javax.swing.GroupLayout jPanel45Layout = new javax.swing.GroupLayout(jPanel45);
        jPanel45.setLayout(jPanel45Layout);
        jPanel45Layout.setHorizontalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel45Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel45Layout.setVerticalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel45Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelSubOutputKekMSalesmanLayout = new javax.swing.GroupLayout(jPanelSubOutputKekMSalesman);
        jPanelSubOutputKekMSalesman.setLayout(jPanelSubOutputKekMSalesmanLayout);
        jPanelSubOutputKekMSalesmanLayout.setHorizontalGroup(
            jPanelSubOutputKekMSalesmanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubOutputKekMSalesmanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSubOutputKekMSalesmanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelSubOutputKekMSalesmanLayout.setVerticalGroup(
            jPanelSubOutputKekMSalesmanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSubOutputKekMSalesmanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneUtamaOutputKEK.addTab("MSalesman", jPanelSubOutputKekMSalesman);

        jPanel46.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnOutputTStokReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/sync_16x16.png"))); // NOI18N
        btnOutputTStokReload.setText("Reload");

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel46Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOutputTStokReload, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(845, Short.MAX_VALUE))
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel46Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOutputTStokReload)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel47.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tableOutputTStok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane12.setViewportView(tableOutputTStok);

        javax.swing.GroupLayout jPanel47Layout = new javax.swing.GroupLayout(jPanel47);
        jPanel47.setLayout(jPanel47Layout);
        jPanel47Layout.setHorizontalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel47Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel47Layout.setVerticalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel47Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelSubOutputKekTStokLayout = new javax.swing.GroupLayout(jPanelSubOutputKekTStok);
        jPanelSubOutputKekTStok.setLayout(jPanelSubOutputKekTStokLayout);
        jPanelSubOutputKekTStokLayout.setHorizontalGroup(
            jPanelSubOutputKekTStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubOutputKekTStokLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSubOutputKekTStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel46, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelSubOutputKekTStokLayout.setVerticalGroup(
            jPanelSubOutputKekTStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSubOutputKekTStokLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPaneUtamaOutputKEK.addTab("TStok", jPanelSubOutputKekTStok);

        jPanel48.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnOutputTOutletReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/sync_16x16.png"))); // NOI18N
        btnOutputTOutletReload.setText("Reload");

        javax.swing.GroupLayout jPanel48Layout = new javax.swing.GroupLayout(jPanel48);
        jPanel48.setLayout(jPanel48Layout);
        jPanel48Layout.setHorizontalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel48Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOutputTOutletReload, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(845, Short.MAX_VALUE))
        );
        jPanel48Layout.setVerticalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel48Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOutputTOutletReload)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel49.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tableOutputTOutlet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane13.setViewportView(tableOutputTOutlet);

        javax.swing.GroupLayout jPanel49Layout = new javax.swing.GroupLayout(jPanel49);
        jPanel49.setLayout(jPanel49Layout);
        jPanel49Layout.setHorizontalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel49Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel49Layout.setVerticalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel49Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelSubOutputKekMsloutLayout = new javax.swing.GroupLayout(jPanelSubOutputKekMslout);
        jPanelSubOutputKekMslout.setLayout(jPanelSubOutputKekMsloutLayout);
        jPanelSubOutputKekMsloutLayout.setHorizontalGroup(
            jPanelSubOutputKekMsloutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubOutputKekMsloutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSubOutputKekMsloutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelSubOutputKekMsloutLayout.setVerticalGroup(
            jPanelSubOutputKekMsloutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSubOutputKekMsloutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPaneUtamaOutputKEK.addTab("MSlout", jPanelSubOutputKekMslout);

        jPanel50.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnOutputTDatdslReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/sync_16x16.png"))); // NOI18N
        btnOutputTDatdslReload.setText("Reload");

        lblOutputTDatdslFooterInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOutputTDatdslFooterInfo.setText("lblOutputTDatdslFooterInfo");

        javax.swing.GroupLayout jPanel50Layout = new javax.swing.GroupLayout(jPanel50);
        jPanel50.setLayout(jPanel50Layout);
        jPanel50Layout.setHorizontalGroup(
            jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel50Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOutputTDatdslReload, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(lblOutputTDatdslFooterInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel50Layout.setVerticalGroup(
            jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel50Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOutputTDatdslReload)
                    .addComponent(lblOutputTDatdslFooterInfo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel51.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tableOutputTDatdsl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane14.setViewportView(tableOutputTDatdsl);

        javax.swing.GroupLayout jPanel51Layout = new javax.swing.GroupLayout(jPanel51);
        jPanel51.setLayout(jPanel51Layout);
        jPanel51Layout.setHorizontalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel51Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane14)
                .addContainerGap())
        );
        jPanel51Layout.setVerticalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel51Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelSubOutputKekTdatdslLayout = new javax.swing.GroupLayout(jPanelSubOutputKekTdatdsl);
        jPanelSubOutputKekTdatdsl.setLayout(jPanelSubOutputKekTdatdslLayout);
        jPanelSubOutputKekTdatdslLayout.setHorizontalGroup(
            jPanelSubOutputKekTdatdslLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubOutputKekTdatdslLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSubOutputKekTdatdslLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelSubOutputKekTdatdslLayout.setVerticalGroup(
            jPanelSubOutputKekTdatdslLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSubOutputKekTdatdslLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPaneUtamaOutputKEK.addTab("TDATDSL (Sales)", jPanelSubOutputKekTdatdsl);

        jPanel83.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnOutputTDatdsrReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/sync_16x16.png"))); // NOI18N
        btnOutputTDatdsrReload.setText("Reload");

        lblOutputTDatdsrFooterInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOutputTDatdsrFooterInfo.setText("lblOutputTDatdsrFooterInfo");

        javax.swing.GroupLayout jPanel83Layout = new javax.swing.GroupLayout(jPanel83);
        jPanel83.setLayout(jPanel83Layout);
        jPanel83Layout.setHorizontalGroup(
            jPanel83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel83Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOutputTDatdsrReload, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel83Layout.createSequentialGroup()
                    .addContainerGap(222, Short.MAX_VALUE)
                    .addComponent(lblOutputTDatdsrFooterInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(38, 38, 38)))
        );
        jPanel83Layout.setVerticalGroup(
            jPanel83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel83Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOutputTDatdsrReload)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel83Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lblOutputTDatdsrFooterInfo)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );

        tableOutputTDatdsr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane33.setViewportView(tableOutputTDatdsr);

        javax.swing.GroupLayout jPanelSubOutputKekTdatdsrLayout = new javax.swing.GroupLayout(jPanelSubOutputKekTdatdsr);
        jPanelSubOutputKekTdatdsr.setLayout(jPanelSubOutputKekTdatdsrLayout);
        jPanelSubOutputKekTdatdsrLayout.setHorizontalGroup(
            jPanelSubOutputKekTdatdsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubOutputKekTdatdsrLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSubOutputKekTdatdsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel83, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane33, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanelSubOutputKekTdatdsrLayout.setVerticalGroup(
            jPanelSubOutputKekTdatdsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSubOutputKekTdatdsrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane33, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jTabbedPaneUtamaOutputKEK.addTab("TDATDSR (Retur)", jPanelSubOutputKekTdatdsr);

        jPanel84.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnOutputTDatdprReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/sync_16x16.png"))); // NOI18N
        btnOutputTDatdprReload.setText("Reload");

        lblOutputTDatdprFooterInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOutputTDatdprFooterInfo.setText("lblOutputTDatdprFooterInfo");

        javax.swing.GroupLayout jPanel84Layout = new javax.swing.GroupLayout(jPanel84);
        jPanel84.setLayout(jPanel84Layout);
        jPanel84Layout.setHorizontalGroup(
            jPanel84Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel84Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOutputTDatdprReload, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(lblOutputTDatdprFooterInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel84Layout.setVerticalGroup(
            jPanel84Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel84Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel84Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOutputTDatdprReload)
                    .addComponent(lblOutputTDatdprFooterInfo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableOutputTDatdpr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane34.setViewportView(tableOutputTDatdpr);

        javax.swing.GroupLayout jPanelSubOutputKekTdatdprLayout = new javax.swing.GroupLayout(jPanelSubOutputKekTdatdpr);
        jPanelSubOutputKekTdatdpr.setLayout(jPanelSubOutputKekTdatdprLayout);
        jPanelSubOutputKekTdatdprLayout.setHorizontalGroup(
            jPanelSubOutputKekTdatdprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSubOutputKekTdatdprLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSubOutputKekTdatdprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane34, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                    .addComponent(jPanel84, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        jPanelSubOutputKekTdatdprLayout.setVerticalGroup(
            jPanelSubOutputKekTdatdprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSubOutputKekTdatdprLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane34, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        jTabbedPaneUtamaOutputKEK.addTab("TDATDPR (Barang Datang)", jPanelSubOutputKekTdatdpr);

        jPanel85.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnOutputTDatsriReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/sync_16x16.png"))); // NOI18N
        btnOutputTDatsriReload.setText("Reload");

        lblOutputTDatsriFooterInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOutputTDatsriFooterInfo.setText("lblOutputTDatsriFooterInfo");

        javax.swing.GroupLayout jPanel85Layout = new javax.swing.GroupLayout(jPanel85);
        jPanel85.setLayout(jPanel85Layout);
        jPanel85Layout.setHorizontalGroup(
            jPanel85Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel85Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOutputTDatsriReload, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(lblOutputTDatsriFooterInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel85Layout.setVerticalGroup(
            jPanel85Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel85Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel85Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOutputTDatsriReload)
                    .addComponent(lblOutputTDatsriFooterInfo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableOutputTDatsri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane35.setViewportView(tableOutputTDatsri);

        javax.swing.GroupLayout jPanelSubOutputKekTdatsriLayout = new javax.swing.GroupLayout(jPanelSubOutputKekTdatsri);
        jPanelSubOutputKekTdatsri.setLayout(jPanelSubOutputKekTdatsriLayout);
        jPanelSubOutputKekTdatsriLayout.setHorizontalGroup(
            jPanelSubOutputKekTdatsriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSubOutputKekTdatsriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSubOutputKekTdatsriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane35, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                    .addComponent(jPanel85, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        jPanelSubOutputKekTdatsriLayout.setVerticalGroup(
            jPanelSubOutputKekTdatsriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSubOutputKekTdatsriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane35, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        jTabbedPaneUtamaOutputKEK.addTab("TDATSRI (Retur ke Principal)", jPanelSubOutputKekTdatsri);

        jPanel86.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnOutputTAdjstkReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/sync_16x16.png"))); // NOI18N
        btnOutputTAdjstkReload.setText("Reload");

        lblOutputTAdjstkFooterInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOutputTAdjstkFooterInfo.setText("lblOutputTAdjstkFooterInfo");

        javax.swing.GroupLayout jPanel86Layout = new javax.swing.GroupLayout(jPanel86);
        jPanel86.setLayout(jPanel86Layout);
        jPanel86Layout.setHorizontalGroup(
            jPanel86Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel86Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOutputTAdjstkReload, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(lblOutputTAdjstkFooterInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel86Layout.setVerticalGroup(
            jPanel86Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel86Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel86Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOutputTAdjstkReload)
                    .addComponent(lblOutputTAdjstkFooterInfo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableOutputTAdjstk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane36.setViewportView(tableOutputTAdjstk);

        javax.swing.GroupLayout jPanelSubOutputKekTadjstkLayout = new javax.swing.GroupLayout(jPanelSubOutputKekTadjstk);
        jPanelSubOutputKekTadjstk.setLayout(jPanelSubOutputKekTadjstkLayout);
        jPanelSubOutputKekTadjstkLayout.setHorizontalGroup(
            jPanelSubOutputKekTadjstkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSubOutputKekTadjstkLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSubOutputKekTadjstkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane36, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
                    .addComponent(jPanel86, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanelSubOutputKekTadjstkLayout.setVerticalGroup(
            jPanelSubOutputKekTadjstkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSubOutputKekTadjstkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane36, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel86, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        jTabbedPaneUtamaOutputKEK.addTab("TADJSTK", jPanelSubOutputKekTadjstk);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneUtamaOutputKEK, javax.swing.GroupLayout.PREFERRED_SIZE, 1025, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPaneUtamaOutputKEK, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOutputTAdjstkReload;
    private javax.swing.JButton btnOutputTDatdprReload;
    private javax.swing.JButton btnOutputTDatdslReload;
    private javax.swing.JButton btnOutputTDatdsrReload;
    private javax.swing.JButton btnOutputTDatsriReload;
    private javax.swing.JButton btnOutputTOutletReload;
    private javax.swing.JButton btnOutputTSalesmanReload;
    private javax.swing.JButton btnOutputTStokReload;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel83;
    private javax.swing.JPanel jPanel84;
    private javax.swing.JPanel jPanel85;
    private javax.swing.JPanel jPanel86;
    private javax.swing.JPanel jPanelSubOutputKekMSalesman;
    private javax.swing.JPanel jPanelSubOutputKekMslout;
    private javax.swing.JPanel jPanelSubOutputKekTStok;
    private javax.swing.JPanel jPanelSubOutputKekTadjstk;
    private javax.swing.JPanel jPanelSubOutputKekTdatdpr;
    private javax.swing.JPanel jPanelSubOutputKekTdatdsl;
    private javax.swing.JPanel jPanelSubOutputKekTdatdsr;
    private javax.swing.JPanel jPanelSubOutputKekTdatsri;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane33;
    private javax.swing.JScrollPane jScrollPane34;
    private javax.swing.JScrollPane jScrollPane35;
    private javax.swing.JScrollPane jScrollPane36;
    private javax.swing.JTabbedPane jTabbedPaneUtamaOutputKEK;
    private javax.swing.JLabel lblOutputTAdjstkFooterInfo;
    private javax.swing.JLabel lblOutputTDatdprFooterInfo;
    private javax.swing.JLabel lblOutputTDatdslFooterInfo;
    private javax.swing.JLabel lblOutputTDatdsrFooterInfo;
    private javax.swing.JLabel lblOutputTDatsriFooterInfo;
    private javax.swing.JTable tableOutputTAdjstk;
    private javax.swing.JTable tableOutputTDatdpr;
    private javax.swing.JTable tableOutputTDatdsl;
    private javax.swing.JTable tableOutputTDatdsr;
    private javax.swing.JTable tableOutputTDatsri;
    private javax.swing.JTable tableOutputTOutlet;
    private javax.swing.JTable tableOutputTSalesman;
    private javax.swing.JTable tableOutputTStok;
    // End of variables declaration//GEN-END:variables
}
