/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.dimas.bridging.app.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTable;

/**
 *
 * @author yhawin
 */
public class JPanelSubOutputPokari extends javax.swing.JPanel {

    /**
     * Creates new form JPanelSubOutputPokari
     */
    public JPanelSubOutputPokari() {
        initComponents();
    }

    public JButton getBtnOutputPokariArCustomerReload() {
        return btnOutputPokariArCustomerReload;
    }

    public JButton getBtnOutputPokariCanDDeliveryOrderDetailReload() {
        return btnOutputPokariCanDDeliveryOrderDetailReload;
    }

    public JButton getBtnOutputPokariCanDDeliveryOrderDiscReload() {
        return btnOutputPokariCanDDeliveryOrderDiscReload;
    }

    public JButton getBtnOutputPokariCanDDeliveryOrderReload() {
        return btnOutputPokariCanDDeliveryOrderReload;
    }

    public JButton getBtnOutputPokariEmployeeTargetItemDetailReload() {
        return btnOutputPokariEmployeeTargetItemDetailReload;
    }

    public JButton getBtnOutputPokariEmployeeTargetReload() {
        return btnOutputPokariEmployeeTargetReload;
    }

    public JButton getBtnOutputPokariSpEmployeeReload() {
        return btnOutputPokariSpEmployeeReload;
    }

    public JPanel getjPanelOutputPokariArCustomer() {
        return jPanelOutputPokariArCustomer;
    }

    public JPanel getjPanelOutputPokariCanDDeliveryOrder() {
        return jPanelOutputPokariCanDDeliveryOrder;
    }

    public JPanel getjPanelOutputPokariCanDDeliveryOrderDetail() {
        return jPanelOutputPokariCanDDeliveryOrderDetail;
    }

    public JPanel getjPanelOutputPokariCanDDeliveryOrderDisc() {
        return jPanelOutputPokariCanDDeliveryOrderDisc;
    }

    public JPanel getjPanelOutputPokariSpEmployee() {
        return jPanelOutputPokariSpEmployee;
    }

    public JPanel getjPanelOutputPokariSpEmployeeTarget() {
        return jPanelOutputPokariSpEmployeeTarget;
    }

    public JPanel getjPanelOutputPokariSpEmployeeTargetDetail() {
        return jPanelOutputPokariSpEmployeeTargetDetail;
    }

    public JTabbedPane getjTabbedPaneUtamaOutputPokari() {
        return jTabbedPaneUtamaOutputPokari;
    }

    public JLabel getLabelOutputPokariArCustomerFooter() {
        return labelOutputPokariArCustomerFooter;
    }

    public JLabel getLabelOutputPokariCanDDeliveryOrderDetailFooter() {
        return labelOutputPokariCanDDeliveryOrderDetailFooter;
    }

    public JLabel getLabelOutputPokariCanDDeliveryOrderDiscFooter() {
        return labelOutputPokariCanDDeliveryOrderDiscFooter;
    }

    public JLabel getLabelOutputPokariCanDDeliveryOrderFooter() {
        return labelOutputPokariCanDDeliveryOrderFooter;
    }

    public JLabel getLabelOutputPokariEmployeeTargetDetailFooter() {
        return labelOutputPokariEmployeeTargetDetailFooter;
    }

    public JLabel getLabelOutputPokariEmployeeTargetFooter() {
        return labelOutputPokariEmployeeTargetFooter;
    }

    public JLabel getLabelOutputPokariSpEmployeeFooter() {
        return labelOutputPokariSpEmployeeFooter;
    }

    public JTable getTableOutputPokariArCustomer() {
        return tableOutputPokariArCustomer;
    }

    public JTable getTableOutputPokariCanDDeliveryOrder() {
        return tableOutputPokariCanDDeliveryOrder;
    }

    public JTable getTableOutputPokariCanDDeliveryOrderDetail() {
        return tableOutputPokariCanDDeliveryOrderDetail;
    }

    public JTable getTableOutputPokariCanDDeliveryOrderDisc() {
        return tableOutputPokariCanDDeliveryOrderDisc;
    }

    public JTable getTableOutputPokariEmployeeTarget() {
        return tableOutputPokariEmployeeTarget;
    }

    public JTable getTableOutputPokariEmployeeTargetDetail() {
        return tableOutputPokariEmployeeTargetDetail;
    }

    public JTable getTableOutputPokariSpEmployee() {
        return tableOutputPokariSpEmployee;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneUtamaOutputPokari = new javax.swing.JTabbedPane();
        jPanelOutputPokariArCustomer = new javax.swing.JPanel();
        jPanel73 = new javax.swing.JPanel();
        btnOutputPokariArCustomerReload = new javax.swing.JButton();
        labelOutputPokariArCustomerFooter = new javax.swing.JLabel();
        jPanel74 = new javax.swing.JPanel();
        jScrollPane41 = new javax.swing.JScrollPane();
        tableOutputPokariArCustomer = new javax.swing.JTable();
        jPanelOutputPokariCanDDeliveryOrder = new javax.swing.JPanel();
        jPanel75 = new javax.swing.JPanel();
        btnOutputPokariCanDDeliveryOrderReload = new javax.swing.JButton();
        labelOutputPokariCanDDeliveryOrderFooter = new javax.swing.JLabel();
        jPanel79 = new javax.swing.JPanel();
        jScrollPane42 = new javax.swing.JScrollPane();
        tableOutputPokariCanDDeliveryOrder = new javax.swing.JTable();
        jPanelOutputPokariCanDDeliveryOrderDetail = new javax.swing.JPanel();
        jPanel80 = new javax.swing.JPanel();
        btnOutputPokariCanDDeliveryOrderDetailReload = new javax.swing.JButton();
        labelOutputPokariCanDDeliveryOrderDetailFooter = new javax.swing.JLabel();
        jPanel81 = new javax.swing.JPanel();
        jScrollPane43 = new javax.swing.JScrollPane();
        tableOutputPokariCanDDeliveryOrderDetail = new javax.swing.JTable();
        jPanelOutputPokariSpEmployee = new javax.swing.JPanel();
        jPanel82 = new javax.swing.JPanel();
        btnOutputPokariSpEmployeeReload = new javax.swing.JButton();
        labelOutputPokariSpEmployeeFooter = new javax.swing.JLabel();
        jPanel93 = new javax.swing.JPanel();
        jScrollPane44 = new javax.swing.JScrollPane();
        tableOutputPokariSpEmployee = new javax.swing.JTable();
        jPanelOutputPokariSpEmployeeTarget = new javax.swing.JPanel();
        jPanel94 = new javax.swing.JPanel();
        btnOutputPokariEmployeeTargetReload = new javax.swing.JButton();
        labelOutputPokariEmployeeTargetFooter = new javax.swing.JLabel();
        jPanel95 = new javax.swing.JPanel();
        jScrollPane45 = new javax.swing.JScrollPane();
        tableOutputPokariEmployeeTarget = new javax.swing.JTable();
        jPanelOutputPokariSpEmployeeTargetDetail = new javax.swing.JPanel();
        jPanel96 = new javax.swing.JPanel();
        btnOutputPokariEmployeeTargetItemDetailReload = new javax.swing.JButton();
        labelOutputPokariEmployeeTargetDetailFooter = new javax.swing.JLabel();
        jPanel97 = new javax.swing.JPanel();
        jScrollPane46 = new javax.swing.JScrollPane();
        tableOutputPokariEmployeeTargetDetail = new javax.swing.JTable();
        jPanelOutputPokariCanDDeliveryOrderDisc = new javax.swing.JPanel();
        jPanel100 = new javax.swing.JPanel();
        btnOutputPokariCanDDeliveryOrderDiscReload = new javax.swing.JButton();
        labelOutputPokariCanDDeliveryOrderDiscFooter = new javax.swing.JLabel();
        jPanel101 = new javax.swing.JPanel();
        jScrollPane50 = new javax.swing.JScrollPane();
        tableOutputPokariCanDDeliveryOrderDisc = new javax.swing.JTable();

        jPanel73.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnOutputPokariArCustomerReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/sync_16x16.png"))); // NOI18N
        btnOutputPokariArCustomerReload.setText("Reload");

        labelOutputPokariArCustomerFooter.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelOutputPokariArCustomerFooter.setText("jLabel87");
        labelOutputPokariArCustomerFooter.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel73Layout = new javax.swing.GroupLayout(jPanel73);
        jPanel73.setLayout(jPanel73Layout);
        jPanel73Layout.setHorizontalGroup(
            jPanel73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel73Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOutputPokariArCustomerReload, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelOutputPokariArCustomerFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel73Layout.setVerticalGroup(
            jPanel73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel73Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel73Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(labelOutputPokariArCustomerFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel73Layout.createSequentialGroup()
                        .addComponent(btnOutputPokariArCustomerReload)
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel74.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tableOutputPokariArCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane41.setViewportView(tableOutputPokariArCustomer);

        javax.swing.GroupLayout jPanel74Layout = new javax.swing.GroupLayout(jPanel74);
        jPanel74.setLayout(jPanel74Layout);
        jPanel74Layout.setHorizontalGroup(
            jPanel74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel74Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane41, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel74Layout.setVerticalGroup(
            jPanel74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel74Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane41, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelOutputPokariArCustomerLayout = new javax.swing.GroupLayout(jPanelOutputPokariArCustomer);
        jPanelOutputPokariArCustomer.setLayout(jPanelOutputPokariArCustomerLayout);
        jPanelOutputPokariArCustomerLayout.setHorizontalGroup(
            jPanelOutputPokariArCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOutputPokariArCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOutputPokariArCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel74, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel73, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelOutputPokariArCustomerLayout.setVerticalGroup(
            jPanelOutputPokariArCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOutputPokariArCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPaneUtamaOutputPokari.addTab("Ar Customer", jPanelOutputPokariArCustomer);

        jPanel75.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnOutputPokariCanDDeliveryOrderReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/sync_16x16.png"))); // NOI18N
        btnOutputPokariCanDDeliveryOrderReload.setText("Reload");

        labelOutputPokariCanDDeliveryOrderFooter.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelOutputPokariCanDDeliveryOrderFooter.setText("jLabel87");
        labelOutputPokariCanDDeliveryOrderFooter.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel75Layout = new javax.swing.GroupLayout(jPanel75);
        jPanel75.setLayout(jPanel75Layout);
        jPanel75Layout.setHorizontalGroup(
            jPanel75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel75Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOutputPokariCanDDeliveryOrderReload, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelOutputPokariCanDDeliveryOrderFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel75Layout.setVerticalGroup(
            jPanel75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel75Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelOutputPokariCanDDeliveryOrderFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOutputPokariCanDDeliveryOrderReload))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel79.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tableOutputPokariCanDDeliveryOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane42.setViewportView(tableOutputPokariCanDDeliveryOrder);

        javax.swing.GroupLayout jPanel79Layout = new javax.swing.GroupLayout(jPanel79);
        jPanel79.setLayout(jPanel79Layout);
        jPanel79Layout.setHorizontalGroup(
            jPanel79Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel79Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane42, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel79Layout.setVerticalGroup(
            jPanel79Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel79Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane42, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelOutputPokariCanDDeliveryOrderLayout = new javax.swing.GroupLayout(jPanelOutputPokariCanDDeliveryOrder);
        jPanelOutputPokariCanDDeliveryOrder.setLayout(jPanelOutputPokariCanDDeliveryOrderLayout);
        jPanelOutputPokariCanDDeliveryOrderLayout.setHorizontalGroup(
            jPanelOutputPokariCanDDeliveryOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOutputPokariCanDDeliveryOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOutputPokariCanDDeliveryOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel79, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel75, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelOutputPokariCanDDeliveryOrderLayout.setVerticalGroup(
            jPanelOutputPokariCanDDeliveryOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOutputPokariCanDDeliveryOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel79, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPaneUtamaOutputPokari.addTab("Can DDeliveryOrder", jPanelOutputPokariCanDDeliveryOrder);

        jPanel80.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnOutputPokariCanDDeliveryOrderDetailReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/sync_16x16.png"))); // NOI18N
        btnOutputPokariCanDDeliveryOrderDetailReload.setText("Reload");

        labelOutputPokariCanDDeliveryOrderDetailFooter.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelOutputPokariCanDDeliveryOrderDetailFooter.setText("jLabel87");
        labelOutputPokariCanDDeliveryOrderDetailFooter.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel80Layout = new javax.swing.GroupLayout(jPanel80);
        jPanel80.setLayout(jPanel80Layout);
        jPanel80Layout.setHorizontalGroup(
            jPanel80Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel80Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOutputPokariCanDDeliveryOrderDetailReload, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelOutputPokariCanDDeliveryOrderDetailFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel80Layout.setVerticalGroup(
            jPanel80Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel80Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel80Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel80Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(labelOutputPokariCanDDeliveryOrderDetailFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel80Layout.createSequentialGroup()
                        .addComponent(btnOutputPokariCanDDeliveryOrderDetailReload)
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel81.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tableOutputPokariCanDDeliveryOrderDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane43.setViewportView(tableOutputPokariCanDDeliveryOrderDetail);

        javax.swing.GroupLayout jPanel81Layout = new javax.swing.GroupLayout(jPanel81);
        jPanel81.setLayout(jPanel81Layout);
        jPanel81Layout.setHorizontalGroup(
            jPanel81Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel81Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane43, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel81Layout.setVerticalGroup(
            jPanel81Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel81Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane43, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelOutputPokariCanDDeliveryOrderDetailLayout = new javax.swing.GroupLayout(jPanelOutputPokariCanDDeliveryOrderDetail);
        jPanelOutputPokariCanDDeliveryOrderDetail.setLayout(jPanelOutputPokariCanDDeliveryOrderDetailLayout);
        jPanelOutputPokariCanDDeliveryOrderDetailLayout.setHorizontalGroup(
            jPanelOutputPokariCanDDeliveryOrderDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOutputPokariCanDDeliveryOrderDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOutputPokariCanDDeliveryOrderDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel81, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel80, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelOutputPokariCanDDeliveryOrderDetailLayout.setVerticalGroup(
            jPanelOutputPokariCanDDeliveryOrderDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOutputPokariCanDDeliveryOrderDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPaneUtamaOutputPokari.addTab("Can DDeliveryOrder Detail", jPanelOutputPokariCanDDeliveryOrderDetail);

        jPanel82.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnOutputPokariSpEmployeeReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/sync_16x16.png"))); // NOI18N
        btnOutputPokariSpEmployeeReload.setText("Reload");

        labelOutputPokariSpEmployeeFooter.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelOutputPokariSpEmployeeFooter.setText("jLabel87");
        labelOutputPokariSpEmployeeFooter.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel82Layout = new javax.swing.GroupLayout(jPanel82);
        jPanel82.setLayout(jPanel82Layout);
        jPanel82Layout.setHorizontalGroup(
            jPanel82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel82Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOutputPokariSpEmployeeReload, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelOutputPokariSpEmployeeFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel82Layout.setVerticalGroup(
            jPanel82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel82Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel82Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(labelOutputPokariSpEmployeeFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel82Layout.createSequentialGroup()
                        .addComponent(btnOutputPokariSpEmployeeReload)
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel93.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tableOutputPokariSpEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane44.setViewportView(tableOutputPokariSpEmployee);

        javax.swing.GroupLayout jPanel93Layout = new javax.swing.GroupLayout(jPanel93);
        jPanel93.setLayout(jPanel93Layout);
        jPanel93Layout.setHorizontalGroup(
            jPanel93Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel93Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane44, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel93Layout.setVerticalGroup(
            jPanel93Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel93Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane44, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelOutputPokariSpEmployeeLayout = new javax.swing.GroupLayout(jPanelOutputPokariSpEmployee);
        jPanelOutputPokariSpEmployee.setLayout(jPanelOutputPokariSpEmployeeLayout);
        jPanelOutputPokariSpEmployeeLayout.setHorizontalGroup(
            jPanelOutputPokariSpEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOutputPokariSpEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOutputPokariSpEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel93, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel82, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelOutputPokariSpEmployeeLayout.setVerticalGroup(
            jPanelOutputPokariSpEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOutputPokariSpEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel93, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPaneUtamaOutputPokari.addTab("Sp Employee", jPanelOutputPokariSpEmployee);

        jPanel94.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnOutputPokariEmployeeTargetReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/sync_16x16.png"))); // NOI18N
        btnOutputPokariEmployeeTargetReload.setText("Reload");

        labelOutputPokariEmployeeTargetFooter.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelOutputPokariEmployeeTargetFooter.setText("jLabel87");
        labelOutputPokariEmployeeTargetFooter.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel94Layout = new javax.swing.GroupLayout(jPanel94);
        jPanel94.setLayout(jPanel94Layout);
        jPanel94Layout.setHorizontalGroup(
            jPanel94Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel94Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOutputPokariEmployeeTargetReload, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelOutputPokariEmployeeTargetFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel94Layout.setVerticalGroup(
            jPanel94Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel94Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel94Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelOutputPokariEmployeeTargetFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOutputPokariEmployeeTargetReload))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel95.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tableOutputPokariEmployeeTarget.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane45.setViewportView(tableOutputPokariEmployeeTarget);

        javax.swing.GroupLayout jPanel95Layout = new javax.swing.GroupLayout(jPanel95);
        jPanel95.setLayout(jPanel95Layout);
        jPanel95Layout.setHorizontalGroup(
            jPanel95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel95Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane45, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel95Layout.setVerticalGroup(
            jPanel95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel95Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane45, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelOutputPokariSpEmployeeTargetLayout = new javax.swing.GroupLayout(jPanelOutputPokariSpEmployeeTarget);
        jPanelOutputPokariSpEmployeeTarget.setLayout(jPanelOutputPokariSpEmployeeTargetLayout);
        jPanelOutputPokariSpEmployeeTargetLayout.setHorizontalGroup(
            jPanelOutputPokariSpEmployeeTargetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOutputPokariSpEmployeeTargetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOutputPokariSpEmployeeTargetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel95, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel94, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelOutputPokariSpEmployeeTargetLayout.setVerticalGroup(
            jPanelOutputPokariSpEmployeeTargetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOutputPokariSpEmployeeTargetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel95, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel94, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPaneUtamaOutputPokari.addTab("Sp EmployeeTarget", jPanelOutputPokariSpEmployeeTarget);

        jPanel96.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnOutputPokariEmployeeTargetItemDetailReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/sync_16x16.png"))); // NOI18N
        btnOutputPokariEmployeeTargetItemDetailReload.setText("Reload");

        labelOutputPokariEmployeeTargetDetailFooter.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelOutputPokariEmployeeTargetDetailFooter.setText("jLabel87");
        labelOutputPokariEmployeeTargetDetailFooter.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel96Layout = new javax.swing.GroupLayout(jPanel96);
        jPanel96.setLayout(jPanel96Layout);
        jPanel96Layout.setHorizontalGroup(
            jPanel96Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel96Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOutputPokariEmployeeTargetItemDetailReload, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelOutputPokariEmployeeTargetDetailFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel96Layout.setVerticalGroup(
            jPanel96Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel96Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel96Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOutputPokariEmployeeTargetItemDetailReload)
                    .addComponent(labelOutputPokariEmployeeTargetDetailFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel97.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tableOutputPokariEmployeeTargetDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane46.setViewportView(tableOutputPokariEmployeeTargetDetail);

        javax.swing.GroupLayout jPanel97Layout = new javax.swing.GroupLayout(jPanel97);
        jPanel97.setLayout(jPanel97Layout);
        jPanel97Layout.setHorizontalGroup(
            jPanel97Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel97Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane46, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel97Layout.setVerticalGroup(
            jPanel97Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel97Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane46, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelOutputPokariSpEmployeeTargetDetailLayout = new javax.swing.GroupLayout(jPanelOutputPokariSpEmployeeTargetDetail);
        jPanelOutputPokariSpEmployeeTargetDetail.setLayout(jPanelOutputPokariSpEmployeeTargetDetailLayout);
        jPanelOutputPokariSpEmployeeTargetDetailLayout.setHorizontalGroup(
            jPanelOutputPokariSpEmployeeTargetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOutputPokariSpEmployeeTargetDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOutputPokariSpEmployeeTargetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel97, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel96, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelOutputPokariSpEmployeeTargetDetailLayout.setVerticalGroup(
            jPanelOutputPokariSpEmployeeTargetDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOutputPokariSpEmployeeTargetDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel97, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel96, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPaneUtamaOutputPokari.addTab("Sp EmployeeTargetDetail", jPanelOutputPokariSpEmployeeTargetDetail);

        jPanel100.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnOutputPokariCanDDeliveryOrderDiscReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dimas/bridging/images/sync_16x16.png"))); // NOI18N
        btnOutputPokariCanDDeliveryOrderDiscReload.setText("Reload");

        labelOutputPokariCanDDeliveryOrderDiscFooter.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelOutputPokariCanDDeliveryOrderDiscFooter.setText("jLabel87");
        labelOutputPokariCanDDeliveryOrderDiscFooter.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel100Layout = new javax.swing.GroupLayout(jPanel100);
        jPanel100.setLayout(jPanel100Layout);
        jPanel100Layout.setHorizontalGroup(
            jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel100Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOutputPokariCanDDeliveryOrderDiscReload, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelOutputPokariCanDDeliveryOrderDiscFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel100Layout.setVerticalGroup(
            jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel100Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOutputPokariCanDDeliveryOrderDiscReload)
                    .addComponent(labelOutputPokariCanDDeliveryOrderDiscFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel101.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tableOutputPokariCanDDeliveryOrderDisc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane50.setViewportView(tableOutputPokariCanDDeliveryOrderDisc);

        javax.swing.GroupLayout jPanel101Layout = new javax.swing.GroupLayout(jPanel101);
        jPanel101.setLayout(jPanel101Layout);
        jPanel101Layout.setHorizontalGroup(
            jPanel101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel101Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane50, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel101Layout.setVerticalGroup(
            jPanel101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel101Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane50, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelOutputPokariCanDDeliveryOrderDiscLayout = new javax.swing.GroupLayout(jPanelOutputPokariCanDDeliveryOrderDisc);
        jPanelOutputPokariCanDDeliveryOrderDisc.setLayout(jPanelOutputPokariCanDDeliveryOrderDiscLayout);
        jPanelOutputPokariCanDDeliveryOrderDiscLayout.setHorizontalGroup(
            jPanelOutputPokariCanDDeliveryOrderDiscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOutputPokariCanDDeliveryOrderDiscLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOutputPokariCanDDeliveryOrderDiscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel101, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel100, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelOutputPokariCanDDeliveryOrderDiscLayout.setVerticalGroup(
            jPanelOutputPokariCanDDeliveryOrderDiscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOutputPokariCanDDeliveryOrderDiscLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPaneUtamaOutputPokari.addTab("Can DDeliveryOrder Disc", jPanelOutputPokariCanDDeliveryOrderDisc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1049, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPaneUtamaOutputPokari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPaneUtamaOutputPokari, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOutputPokariArCustomerReload;
    private javax.swing.JButton btnOutputPokariCanDDeliveryOrderDetailReload;
    private javax.swing.JButton btnOutputPokariCanDDeliveryOrderDiscReload;
    private javax.swing.JButton btnOutputPokariCanDDeliveryOrderReload;
    private javax.swing.JButton btnOutputPokariEmployeeTargetItemDetailReload;
    private javax.swing.JButton btnOutputPokariEmployeeTargetReload;
    private javax.swing.JButton btnOutputPokariSpEmployeeReload;
    private javax.swing.JPanel jPanel100;
    private javax.swing.JPanel jPanel101;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel74;
    private javax.swing.JPanel jPanel75;
    private javax.swing.JPanel jPanel79;
    private javax.swing.JPanel jPanel80;
    private javax.swing.JPanel jPanel81;
    private javax.swing.JPanel jPanel82;
    private javax.swing.JPanel jPanel93;
    private javax.swing.JPanel jPanel94;
    private javax.swing.JPanel jPanel95;
    private javax.swing.JPanel jPanel96;
    private javax.swing.JPanel jPanel97;
    private javax.swing.JPanel jPanelOutputPokariArCustomer;
    private javax.swing.JPanel jPanelOutputPokariCanDDeliveryOrder;
    private javax.swing.JPanel jPanelOutputPokariCanDDeliveryOrderDetail;
    private javax.swing.JPanel jPanelOutputPokariCanDDeliveryOrderDisc;
    private javax.swing.JPanel jPanelOutputPokariSpEmployee;
    private javax.swing.JPanel jPanelOutputPokariSpEmployeeTarget;
    private javax.swing.JPanel jPanelOutputPokariSpEmployeeTargetDetail;
    private javax.swing.JScrollPane jScrollPane41;
    private javax.swing.JScrollPane jScrollPane42;
    private javax.swing.JScrollPane jScrollPane43;
    private javax.swing.JScrollPane jScrollPane44;
    private javax.swing.JScrollPane jScrollPane45;
    private javax.swing.JScrollPane jScrollPane46;
    private javax.swing.JScrollPane jScrollPane50;
    private javax.swing.JTabbedPane jTabbedPaneUtamaOutputPokari;
    private javax.swing.JLabel labelOutputPokariArCustomerFooter;
    private javax.swing.JLabel labelOutputPokariCanDDeliveryOrderDetailFooter;
    private javax.swing.JLabel labelOutputPokariCanDDeliveryOrderDiscFooter;
    private javax.swing.JLabel labelOutputPokariCanDDeliveryOrderFooter;
    private javax.swing.JLabel labelOutputPokariEmployeeTargetDetailFooter;
    private javax.swing.JLabel labelOutputPokariEmployeeTargetFooter;
    private javax.swing.JLabel labelOutputPokariSpEmployeeFooter;
    private javax.swing.JTable tableOutputPokariArCustomer;
    private javax.swing.JTable tableOutputPokariCanDDeliveryOrder;
    private javax.swing.JTable tableOutputPokariCanDDeliveryOrderDetail;
    private javax.swing.JTable tableOutputPokariCanDDeliveryOrderDisc;
    private javax.swing.JTable tableOutputPokariEmployeeTarget;
    private javax.swing.JTable tableOutputPokariEmployeeTargetDetail;
    private javax.swing.JTable tableOutputPokariSpEmployee;
    // End of variables declaration//GEN-END:variables
}
